### ISSUE TITLE
Doesn't work with SQLite

### ISSUE THREAD

**Issue by pMatt1988** [outer-web/image-library#3] opened 2024-03-22 23:02 UTC
Laravel 11 is shipping with SQLite by default now and it seems that image-library does not work with SQLite. I get an error that the FIELD() function does not exist when trying to upload a new image, I was able to solve this by switching to a MySQL database.

**Comment by SimonBroekaert** [comment] 2024-03-24 13:20
Hi @pMatt1988,

You are probably using the Filament package that uses this package? As only the filament package uses a `->orderByRaw('FIELD(id, ' . implode(',', $state) . ')')`.

I will try to solve this issue for you.

Thank you for notifying me!

**Comment by SimonBroekaert** [comment] 2024-03-24 14:01
Hi @pMatt1988 ,

The issue is now resolved by using another way to order the images in the query. The new way is supported by all major DB drivers.

You can use the solution by upgrading to **v2.4.0**

See [the changelog](https://github.com/outer-web/filament-image-library/blob/main/CHANGELOG.md) of the **filament-image-library** as the issue is only present in the filament plugin.

I will mark this as solved, but feel free te re-open if needed!

**Closed by SimonBroekaert** 2024-03-24 14:01 UTC
